FROM ubuntu:24.04

ARG ENV_VAR__TARGET_GPU_CFG_FILE_ALL=docs/notes/containers/config/build_cfg_all.user
ARG ENV_VAR__TARGET_GPU_CFG_FILE_SELECTED=docs/notes/containers/config/build_cfg_cdna.user

ARG ENV_VAR__TARGET_GPU_CFG_FILE_RDNA12=docs/notes/containers/config/build_cfg_rdna1_rdna2.user
ARG ENV_VAR__TARGET_GPU_CFG_FILE_RDNA3=docs/notes/containers/config/build_cfg_rdna3.user
ARG ENV_VAR__TARGET_GPU_CFG_FILE_CDNA=docs/notes/containers/config/build_cfg_cdna.user
ARG ENV_VAR__TARGET_GPU_CFG_FILE=docs/notes/containers/config/build_cfg_cdna.user
ARG ENV_VAR__TARGET_GPU_CFG_FILE_SELECTED=docs/notes/containers/config/build_cfg_cdna.user

WORKDIR /
RUN apt update && apt install -y git git-lfs sudo vim
RUN git clone --recursive https://github.com/lamikr/rocm_sdk_builder.git
RUN cd rocm_sdk_builder && git checkout master

# example how to apply updates to image during the build time
# RUN cd rocm_sdk_builder && git reset --hard HEAD~1 && ./babs.sh -up
RUN cd rocm_sdk_builder && ./docs/notes/containers/docker_build/scripts/preconfig_ubuntu.sh

# build first rocm adk builder base libs for all possible GPU's. 
# Each target gpu increases build time significantly, so it's slow operation
RUN cd rocm_sdk_builder && ./docs/notes/containers/docker_build/scripts/select_target_gpus.sh ${ENV_VAR__TARGET_GPU_CFG_FILE_SELECTED}

# generated commands starts from here
