export ROCM_PATH=${ROCM_HOME}
export HIP_HOME=${ROCM_HOME}
export LLVM_HOME=${ROCM_HOME}
export MAGMA_HOME==${ROCM_HOME}

export LD_LIBRARY_PATH=${ROCM_HOME}/lib64:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${ROCM_HOME}/lib:${LD_LIBRARY_PATH}

export PATH=${ROCM_HOME}/bin:${PATH}



